mariadb:
  image:
    tag: "11.2.3-debian-11-r0"
  # 보조 이미지(Init Container) 설정 추가
  volumePermissions:
    enabled: true
    image:
      tag: "11.2.3-debian-11-r0"
  auth:
    rootPassword: "password123"
    database: "test_db"
  primary:
    persistence:
      enabled: true
      size: 8Gi
