mariadb:
  auth:
    rootPassword: "password123"
    database: "test_db"
  primary:
    # 권한 설정 보조 단계를 아예 꺼버립니다. (에러 원인 제거)
    volumePermissions:
      enabled: false 
    persistence:
      enabled: true
      size: 8Gi
