mariadb:
  image:
    tag: "11.2.3-debian-11-r0"
  # 1. 에러의 주범인 보조 단계를 완전히 비활성화합니다.
  volumePermissions:
    enabled: false
  auth:
    rootPassword: "password123"
    database: "test_db"
  primary:
    persistence:
      enabled: true
      size: 8Gi
